//@version=5
indicator("Switch using an expression", "", true)

ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)

timeframe = input.string(defval="D", title="Time Frame", options=["M", "D", "W", "H", "4H"])
length = input.int(defval=21, title="Lengh", options=[21, 50, 100, 200])
 
high_data = request.security(syminfo.tickerid , timeframe, ta.ema(high, length))
close_data = request.security(syminfo.tickerid, timeframe, ta.ema(close, length))
low_data = request.security(syminfo.tickerid , timeframe, ta.ema(low, length))






high_plot = plot(high_data, linewidth=2, color=color.red)
low_plot = plot(low_data, linewidth=2, color=color.red)
close_plot = plot(close_data, linewidth=1, color=color.red)
// fill(high_plot, low_plot, color=color.red)



