//@version=5
indicator("Switch using an expression", "", true)



timeframe = input.string(defval="1D", title="Time Frame", options=["60", "240", "1D", "1W", "1M"])
length = input.int(defval=21, title="Lengh", options=[21, 50, 100, 150, 200])
moving_average_type = input.string(defval="EMA", title="Moving average type", options=["EMA", "SMA"])

ma(source, length) =>
    switch moving_average_type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)

high_data = request.security(syminfo.tickerid , timeframe, ma(high, length))
close_data = request.security(syminfo.tickerid, timeframe, ma(close, length))
low_data = request.security(syminfo.tickerid , timeframe,  ma(low, length))






high_plot = plot(high_data, linewidth=2, color=color.red)
low_plot = plot(low_data, linewidth=2, color=color.red)
close_plot = plot(close_data, linewidth=1, color=color.red)
// fill(high_plot, low_plot, color=color.red)



